<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;

    protected $table='roles';

    protected $guarded=[];
    protected $fillable=[
        'title',
    ];


    public function getRouteKeyName()
    {
        return 'title'; // TODO: Change the autogenerated stub
    }

    public function hasPermission( Permission $permission)
    {
        return $this->permissions()
            ->where('title', $permission->title)
            ->exists();
    }

    public function Permissions()
    {
        return $this->belongsToMany(Permission::class);
    }

    public static function findByTitle($title)
    {
        return self::query()->whereTitle($title)->firstOrFail();

    }
}
